apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-demo

resources:
  - shared
  - backend
  - frontend

labels:
  - includeSelectors: false
    pairs:
      env: dev
      part-of: devops-takehome
