apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-demo

labels:
  - includeSelectors: false
    pairs:
      env: prod
      part-of: devops-takehome

resources:
  - ../../../base/backend
  - secret.yaml
  - httproute.yaml

configMapGenerator:
  - name: backend-config
    behavior: merge
    envs:
      - configmap.env

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: swr.ap-southeast-2.myhuaweicloud.com/devops-demo/devops-backend
    newTag: blue

patches:
  - path: rollout-patch.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: backend
