apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-tools
  source:
    repoURL: http://gitlab.dwl.internal/infrastructure/gitops/kustomize-demo.git
    targetRevision: main
    path: infrastructure/gitops/tools/argocd-image-updater
    helm:
      releaseName: argocd-image-updater
      # Chart.yaml pins version: 1.2.1 (appVersion v1.2.0)
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    # Manual prune in prod.
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
