apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-demo-prod-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devops-demo
  source:
    repoURL: http://gitlab.dwl.internal/infrastructure/gitops/kustomize-demo.git
    targetRevision: main
    path: overlays/prod/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
