gateway:
  name: envoy-gateway
  namespace: envoy-gateway-system
  sectionNames:
    - http
    - https

routes:
  vault:
    enabled: true
    hostname: vault.example.internal
    namespace: vault
    backend:
      service: hashicorp-vault
      port: 8200
