apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: backend-secrets
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: secret
  path: devops-app/dev/backend
  refreshAfter: 60s
  destination:
    name: backend-secrets
    create: true
  rolloutRestartTargets:
    - kind: argoproj.io/Rollout
      name: backend
